app = "chargebot"
primary_region = "sea"

[env]
  RUST_LOG = "debug"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]
