name: Build, test and push

on:
  push:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - id: set-version
        name: Determine version
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose --release
      - name: Build the Docker image
        run: docker build . --tag andreiko/chargebot:${{ steps.set-version.outputs.version }}
      - name: Push the Docker image
        run: docker push andreiko/chargebot:${{ steps.set-version.outputs.version }}
